### ISSUE TITLE
ERRORS HELP!

### ISSUE THREAD

**Issue by xdark01** [xXKeyleXx/MyPet#862]
17.08 16:49:00 [Server] ERROR Could not pass event EntityDeathEvent to MyPet v2.2.3
17.08 16:49:00 [Server] INFO org.bukkit.event.EventException
17.08 16:49:00 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[zzcustomjar_java8.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
17.08 16:49:00 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[zzcustomjar_java8.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
17.08 16:49:00 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [zzcustomjar_java8.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
17.08 16:49:00 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [zzcustomjar_java8.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
17.08 16:49:00 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:379) [zzcustomjar_java8.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
17.08 16:49:00 [Server] INFO at net.minecraft.server.v1_7_R4.EntityLiving.die(EntityLiving.java:810) [zzcustomjar_java8.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
17.08 16:49:00 [Server] INFO at net.minecraft.server.v1_7_R4.EntityLiving.damageEntity(EntityLiving.java:745) [zzcustomjar_java8.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
17.08 16:49:00 [Server] INFO at net.minecraft.server.v1_7_R4.EntityHuman.attack(EntityHuman.java:950) [zzcustomjar_java8.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
17.08 16:49:00 [Server] INFO at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:1204) [zzcustomjar_java8.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
17.08 16:49:00 [Server] INFO at net.minecraft.server.v1_7_R4.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:37) [zzcustomjar_java8.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
17.08 16:49:00 [Server] INFO at net.minecraft.server.v1_7_R4.PacketPlayInUseEntity.handle(PacketPlayInUseEntity.java:49) [zzcustomjar_java8.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
17.08 16:49:00 [Server] INFO at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [zzcustomjar_java8.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
17.08 16:49:00 [Server] INFO at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [zzcustomjar_java8.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
17.08 16:49:00 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [zzcustomjar_java8.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
17.08 16:49:00 [Server] INFO at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [zzcustomjar_java8.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
17.08 16:49:00 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [zzcustomjar_java8.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
17.08 16:49:00 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [zzcustomjar_java8.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
17.08 16:49:00 [Server] INFO at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [zzcustomjar_java8.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
17.08 16:49:00 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Entity.getName()Ljava/lang/String;
17.08 16:49:00 [Server] INFO at de.Keyle.MyPet.listeners.EntityListener.sendDeathMessage(EntityListener.java:1052) ~[?:?]
17.08 16:49:00 [Server] INFO at de.Keyle.MyPet.listeners.EntityListener.onMyPet(EntityListener.java:899) ~[?:?]
17.08 16:49:00 [Server] INFO at sun.reflect.GeneratedMethodAccessor223.invoke(Unknown Source) ~[?:?]
17.08 16:49:00 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
17.08 16:49:00 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
17.08 16:49:00 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[zzcustomjar_java8.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
17.08 16:49:00 [Server] INFO ... 17 more
[MyPet.docx](https://github.com/xXKeyleXx/MyPet/files/423520/MyPet.docx)

**Comment by xXKeyleXx** [comment]
MC 1.7.9 is not supported by MyPet.

**Comment by xdark01** [comment]
Serious? but the description says it works in 1.7,1.8,1.9 and 1.10 on SpigotMC

**Comment by xXKeyleXx** [comment]
It says "Tested Minecraft Versions: 1.7 1.8 1.9 1.10" because 1.7.10 works fine. But it says 1.7.10-1.10 in the tag line.
