### ISSUE TITLE
java.lang.NoSuchMethodError when executes /petswitch command

### ISSUE THREAD

**Issue by shellljx** [xXKeyleXx/MyPet#848]
Hi Keyle,

My server restarts when a player stored all of his/her pets, and there is an error when the player executes /petswitch command.

My server is running KCauldron version 1.7.10 ,Mypet version 2.1.7.

```
Caused by: java.lang.NoSuchMethodError: de.Keyle.MyPet.compat.v1_7_R4.util.inventory.CustomInventory.setItem(ILnet/minecraft/item/ItemStack;)V
	at de.Keyle.MyPet.compat.v1_7_R4.util.iconmenu.IconMenuInventory.open(IconMenuInventory.java:80) ~[?:?]
	at de.Keyle.MyPet.api.util.inventory.IconMenu.open(IconMenu.java:94) ~[?:?]
	at de.Keyle.MyPet.util.selectionmenu.MyPetSelectionGui.open(MyPetSelectionGui.java:167) ~[?:?]
	at de.Keyle.MyPet.util.selectionmenu.MyPetSelectionGui.open(MyPetSelectionGui.java:65) ~[?:?]
	at de.Keyle.MyPet.commands.CommandSwitch$2.callback(CommandSwitch.java:118) ~[?:?]
	at de.Keyle.MyPet.commands.CommandSwitch$2.callback(CommandSwitch.java:93) ~[?:?]
	at de.Keyle.MyPet.api.repository.RepositoryCallback.run(RepositoryCallback.java:44) ~[?:?]
	at de.Keyle.MyPet.repository.types.NbtRepository.getMyPets(NbtRepository.java:278) ~[?:?]
	at de.Keyle.MyPet.commands.CommandSwitch.onCommand(CommandSwitch.java:93) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-R0.1-SNAPSHOT]
```

**Comment by xXKeyleXx** [comment]
KCauldron is not supported by me. I works fine with a normal 1.7.10CB.
I have no idea what to do to fix that.
